//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo001_Rest
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUERPO_FACTURA
    {
        public int CUE_COD { get; set; }
        public int ENC_CODIGO { get; set; }
        public int PRO_COD { get; set; }
        public int CUE_CANTIDAD { get; set; }
        public decimal CUE_VALORTOTAL { get; set; }
    
    }
}
