//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo001_Rest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENCABEZADO_FACT
    {
    
        public int ENC_CODIGO { get; set; }
        public decimal CL_IDENTIFICACION { get; set; }
        public System.DateTime ENC_AUTORIZACION { get; set; }
        public string ENC_CIUDAD { get; set; }
        public string ENC_FORMAPAGO { get; set; }

    }
}
