//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo001_Rest
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
    
        public int PRO_COD { get; set; }
        public string PRO_NOMBRE { get; set; }
        public decimal PRO_SERIE { get; set; }
        public decimal PRO_COSTO { get; set; }
        public decimal PRO_PVP { get; set; }
        public string PRO_IMAGEN { get; set; }
    
    }
}
